# Generated by Django 5.1.1 on 2024-09-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_autor_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.CharField(blank=True, default='https://pic.pnnet.dev/256x256', max_length=200, null=True),
        ),
    ]
